/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Proceso;
import control.Fecha;
import java.awt.event.ItemEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ModificaPrecio extends javax.swing.JFrame {

    Proceso obj = new Proceso();
    public int auto = 0;

    public ModificaPrecio() {
        initComponents();
        setLocationRelativeTo(null);
        obj.ListaProveedorMarcaModeloAuto(TablaDetalleAuto);

    }

    private String[] rellenaModelos(String dato) {

        String[] informacion = new String[3];

        if (dato.equalsIgnoreCase("SELECCIONAR")) {
            informacion[0] = "SELECCIONAR";
            informacion[1] = "";
            informacion[2] = "";

        }
        if (dato.equalsIgnoreCase("FORD")) {
            informacion[0] = "KA+";
            informacion[1] = "FOCUS";
            informacion[2] = "GALAXY";
        }
        if (dato.equalsIgnoreCase("NISSAN")) {
            informacion[0] = "MICRA";
            informacion[1] = "LEAF";
            informacion[2] = "GT-R";
        }
        if (dato.equalsIgnoreCase("RENAULT")) {
            informacion[0] = "GRAND SCENIC";
            informacion[1] = "KADJAR";
            informacion[2] = "ZOE";
        }
        if (dato.equalsIgnoreCase("KIA")) {
            informacion[0] = "PICANTO";
            informacion[1] = "RIO";
            informacion[2] = "STINGER";
        }
        if (dato.equalsIgnoreCase("HYUNDAI")) {
            informacion[0] = "ELANTRA";
            informacion[1] = "GENESIS";
            informacion[2] = "NEXO";
        }
        if (dato.equalsIgnoreCase("TOYOTA")) {
            informacion[0] = "AYGO";
            informacion[1] = "YARIS";
            informacion[2] = "GT86";
        }
        if (dato.equalsIgnoreCase("CHEVROLET")) {
            informacion[0] = "AVEO";
            informacion[1] = "CAMARO";
            informacion[2] = "SPARK";
        }
        if (dato.equalsIgnoreCase("HONDA")) {
            informacion[0] = "CIVIC 2020";
            informacion[1] = "JAZZ";
            informacion[2] = "VR-V";
        }
        if (dato.equalsIgnoreCase("VOLKSWAGEN")) {
            informacion[0] = "GOLF 2020";
            informacion[1] = "POLO";
            informacion[2] = "T-ROC";
        }

        return informacion;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Modifica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDetalleAuto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Marca = new javax.swing.JComboBox<>();
        Modelo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Color = new javax.swing.JTextField();
        Kilometraje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PrecioNuevo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Modifica.setText("MODIFICAR");
        Modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaActionPerformed(evt);
            }
        });

        TablaDetalleAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaDetalleAuto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDetalleAutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDetalleAuto);

        jLabel2.setText("MARCA");

        Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "CHEVROLET", "FORD", "HONDA", "HYUNDAI", "KIA", "NISSAN", "RENAULT", "TOYOTA", "VOLKSWAGEN" }));
        Marca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MarcaItemStateChanged(evt);
            }
        });
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        Modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        Modelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ModeloItemStateChanged(evt);
            }
        });
        Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloActionPerformed(evt);
            }
        });

        jLabel3.setText("MODELO");

        jLabel4.setText("COLOR");

        Color.setBackground(new java.awt.Color(255, 255, 255));

        Kilometraje.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("KILOMETRAGE");

        Precio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("PRECIO ACTUAL");

        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PrecioNuevo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("PRECIO NUEVO");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("MODIFICAR PRECIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Precio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Color, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Modelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PrecioNuevo)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(Marca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Modifica, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrecioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modifica, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MarcaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.Marca.getSelectedIndex() > 0) {
                this.Modelo.setModel(new DefaultComboBoxModel(this.rellenaModelos(this.Marca.getSelectedItem().toString())));
            }
            obj.ListaMarcaDetallaAutoComprarMarca(TablaDetalleAuto, (String) Marca.getSelectedItem());
        }
    }//GEN-LAST:event_MarcaItemStateChanged

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaActionPerformed

    private void ModeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ModeloItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloItemStateChanged

    private void ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloActionPerformed

    private void ModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaActionPerformed

        if ((Color.getText().equals("")) || (Kilometraje.getText().equals("")) || (((String) Marca.getSelectedItem()).equals("SELECCIONAR")) || (Precio.getText().equals("")) || (PrecioNuevo.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "No deben aver campos vacios");
        } else {
            int idPrecio = obj.IdPrecio((Integer.parseInt(Precio.getText())), (Color.getText()).toUpperCase(), Kilometraje.getText(), (String) Modelo.getSelectedItem());
            if (idPrecio == 0) {
                JOptionPane.showMessageDialog(null, "Id del precio no encontrado");
            } else {

                obj.ModificaPrecio(idPrecio);
                obj.InsertarPrecio(Integer.parseInt(PrecioNuevo.getText()), null, auto);

            }


        }    }//GEN-LAST:event_ModificaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AgregarAuto abrir = new AgregarAuto();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaDetalleAutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDetalleAutoMouseClicked
        int seleccion = TablaDetalleAuto.rowAtPoint(evt.getPoint());
        auto = Integer.parseInt((String.valueOf(TablaDetalleAuto.getValueAt(seleccion, 0))));
        Color.setText(String.valueOf(TablaDetalleAuto.getValueAt(seleccion, 3)));
        Kilometraje.setText(String.valueOf(TablaDetalleAuto.getValueAt(seleccion, 4)));
        Precio.setText(String.valueOf(TablaDetalleAuto.getValueAt(seleccion, 1)));

    }//GEN-LAST:event_TablaDetalleAutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaPrecio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaPrecio().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Color;
    private javax.swing.JTextField Kilometraje;
    private javax.swing.JComboBox<String> Marca;
    private javax.swing.JComboBox<String> Modelo;
    private javax.swing.JButton Modifica;
    private javax.swing.JTextField Precio;
    private javax.swing.JTextField PrecioNuevo;
    private javax.swing.JTable TablaDetalleAuto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
